version: 0.2
phases:
  pre_build:
    commands:
      - echo "Pre-Build stage started"
  build:
    runtime-versions:
      java: openjdk8
    commands:
      - echo "Build stage started"
      - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo "Post build phase started"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*
